- name: Testing Only.
  hosts: all
  remote_user: abhinav
  become: yes
  tasks:

   - name: stopping nginx service
     service: 
        name: nginx
        state: stopped

   - name: Taking pull from bitbucket master branch
     git:
        repo: ssh://bitbucket.org/girnarsoftware/connecto.git
        dest: /data/codebase/connecto
        update: yes
        version: master
        accept_hostkey: yes
        key_file: /home/connecto/.ssh/id_rsa
     become_user: connecto
     become: yes

   - name: starting nginx service
     service: 
        name: nginx
        state: restarted
