- name: Testing Only.
  hosts: all
  tasks:
    - name: Taking pull from bitbucket master branch
      git:
        repo: ssh://bitbucket.org/girnarsoftware/connecto.git
        dest: /data/codebase/connecto
        update: yes
        version: master
        accept_hostkey: yes
        key_file: /home/connecto/.ssh/id_rsa
